%short transmission line
clc; 
clear all;
disp('CALCULATION OF LINE PERFORMANCE OF SHORT TRANSMISSION LINE'); 
P=input('ENTER THE POWER DELIVERED IN W');
V=input('ENTER THE RECEIVING VOLTAGE in kv'); 
V_r = V*10^3/((3)^(1/2));
PF=input('ENTER THE POWER FACTOR');
R=input('ENTER THE Resistance of each conductor'); 
L=input('ENTER THE Inductance of each conductor'); 
Z_ph = R + (1i*L) ;
l_r = P / (3 * V_r*PF); 
sin1 = sin(acos(PF)); 
V_r_vector = V_r;
l_vector = l_r*(PF-(1i*sin1));
V_s_phase = V_r_vector + (l_vector*Z_ph); 
V_s_phase_magnitude = abs(V_s_phase);
V_s_line = 1.732*V_s_phase_magnitude;
Regulation1 = ((V_s_phase_magnitude - V_r) / V_r)*100; 
Line_losses = 3*l_r*l_r*R;
Efficiency1 = (P/ (P+Line_losses)) *100; 
disp('Regulation1');
disp(Regulation1);
disp('Efficiency1');
disp(Efficiency1);


%medium T.L. - nominal T
clc; 
clear all;
disp('CALCULATION FOR MEDIUM LINE NOMINAL T');
P=input('ENTER THE POWER DELIVERED IN W'); 
V=input('ENTER THE RECEIVING VOLTAGE in kv'); 
V_r = V*10^3/1.732;
PF=input('ENTER THE POWER FACTOR');
R=input('ENTER THE Resistance of each conductor'); 
L=input('ENTER THE Inductance of each conductor'); 
Y=input('ENTER THE Admittance of each conductor'); 
Z_ph = R + (1i*L) ;
Y1 =1i* Y;
l_r = P / (1.732*V*1000*PF);
disp('IR'); 
disp(l_r);
A= 1+ (Z_ph*Y1)/2; 
D=A;
disp('A,D=');
disp(A); 
C=Y1;
disp('C='); 
disp(C);
B=Z_ph*(1+ (Z_ph*Y1)/4); 
disp('B=');
disp(B);
sin1 = sin(acos(PF));
V_r_vector = V_r;
l_vector = l_r*(PF-(1i*sin1)); 
disp(l_vector);
V_s_phase = (A*(V_r_vector))+ (B*(l_vector)); 
V_s_phase_magnitude = abs(V_s_phase); 
V_s_line = 1.732*V_s_phase_magnitude; 
disp('V_s_phase_magnitude'); 
disp(V_s_phase_magnitude);
A1 = abs(A);
Regulation1 =(((V_s_phase_magnitude/A1) - V_r) / V_r)*100; 
disp('Regulation');
disp(Regulation1);


%medium nominal pi:
clc; 
clear all; 
clc; 
clear all;
disp('CALCULATION FOR MEDIUM LINE NOMINAL Pl'); 
P=input('ENTER THE POWER DELIVERED IN W'); 
V=input('ENTER THE RECEIVING VOLTAGE in kv');
V_r = V*10^3/1.732;
PF=input('ENTER THE POWER FACTOR');
R=input('ENTER THE Resistance of each conductor'); 
L=input('ENTER THE Inductance of each conductor'); 
Y=input('ENTER THE Admittance of each conductor'); 
Z_ph = R + (1i*L) ;
Y1 =1i *Y;
l_r = P / (1.732*V*1000*PF);
disp('IR'); 
disp(l_r);
A= 1+ (Z_ph*Y1)/2;
D=A;
disp('A,D='); 
disp(A); 
B=Z_ph; 
disp('B='); 
disp(B);
C=Y1*(1+ ((Z_ph*Y1)/4));
disp('C='); 
disp(C);
sin1 = sin(acos(PF)); 
V_r_vector = V_r;
l_vector = l_r*(PF-(1i*sin1)) ; 
disp(l_vector) ;
V_s_phase = (A*(V_r_vector))+ (B*(l_vector)); 
V_s_phase_magnitude = abs(V_s_phase); 
V_s_line = 1.732*V_s_phase_magnitude; 
disp('V_s_phase_magnitude'); 
disp(V_s_phase_magnitude);
disp('sending end current IS'); 
IC2 = (V_s_phase*Y1)/2;
IC1 = (V_r_vector*Y1)/2; 
IL= l_vector + IC1;
IS= IL+ IC2;
disp(IS); 
IS1=abs(IS);
disp('sending end PF'); 
THETA1=(angle(V_s_phase)); 
THETA2=(angle(IS)); 
THETAS=THETA1 - THETA2; 
SENDINGPF= cos(THETAS); 
disp('SENDINGPF'); 
disp(SENDINGPF);
RS=V_r_vector*conj(l_vector); 
disp('RS');
disp(RS); 
RP=real(RS); 
disp('RP'); 
disp(RP); 
RQ=imag(RS);
disp('RQ'); 
disp(RQ);
SS=V_s_phase*conj(IS); 
disp('SS');
disp(SS); 
SP=real(SS); 
disp('SP'); 
disp(SP); 
SQ=imag(SS); 
disp('SQ'); 
disp(SQ); 
disp('efficiency');
sendingp=3*V_s_phase_magnitude*IS1*SENDINGPF; 
disp('sendingp');
disp(sendingp);
eff=(P/(sendingp))*100; 
disp('efficiency:'); 
disp(eff);


%long transmission line
clc; 
clear all;
R=input('Resistance :'); 
L=input('lnductance:');
P = input('ENTER RECEIVING END LOAD IN W :'); 
VRL=input('ENTER RECEIVEING  END VOLTAGE :'); 
Pf=input('ENTER THE RECEIVING END LOAD POWER FACTOR :'); 
Z= R+1i*L;
y=input('ENTER THE Admittance of each conductor'); 
gm=sqrt(z*y);
zc=sqrt(z/y); 
zb=sqrt(y/z); 
A = cosh(gm);
B=zc*sinh(gm); 
C=zb*sinh(gm); 
D=A;
VRP=VRL*1000/(sqrt(3));
l_r = P / (1.732*VRL*1000*Pf); 
Vs=(VRP*A)+ (l_r*B); 
ls=(VRP*C)+(l_r*D);
disp('ls'); 
disp(ls); 
disp('Vs'); 
disp(Vs);
totalpower=3*conj(ls)*Vs; 
disp('totalpower'); 
disp(totalpower);
p=real(totalpower); 
efficiency=(P /p)*100 ; 
disp('efficiency'); 
disp(efficiency);
